//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSettings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSettings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding class specified cannot be null.
        /// </summary>
        internal static string EXCEPTION_BINDING_CLASS_NULL {
            get {
                return ResourceManager.GetString("EXCEPTION_BINDING_CLASS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding with specified key is not found.
        /// </summary>
        internal static string EXCEPTION_BINDING_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXCEPTION_BINDING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler for setting specified is already bound.
        /// </summary>
        internal static string EXCEPTION_DUPLICATE_HANDLER {
            get {
                return ResourceManager.GetString("EXCEPTION_DUPLICATE_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting with specified key is already added.
        /// </summary>
        internal static string EXCEPTION_DUPLICATE_SETTING {
            get {
                return ResourceManager.GetString("EXCEPTION_DUPLICATE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler for setting specified cannot be null.
        /// </summary>
        internal static string EXCEPTION_HANDLER_NULL {
            get {
                return ResourceManager.GetString("EXCEPTION_HANDLER_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting with specified key is not found.
        /// </summary>
        internal static string EXCEPTION_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXCEPTION_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting with specified key is not set.
        /// </summary>
        internal static string EXCEPTION_KEY_NOT_SET {
            get {
                return ResourceManager.GetString("EXCEPTION_KEY_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting with specified key is a different type than expected.
        /// </summary>
        internal static string EXCEPTION_TYPE_MISMATCH {
            get {
                return ResourceManager.GetString("EXCEPTION_TYPE_MISMATCH", resourceCulture);
            }
        }
    }
}
